version: "2.3"
services:
  # PaddleSeg
  paddleseg:
    runtime: nvidia
    build:
      context: ./docker
      dockerfile: Dockerfile
      args:
        CUDA: 11.0
        CUDNN: 8
    tty: true
    volumes:
      - ./output:/paddleseg/output
      - ./data:/paddleseg/data
    ports:
      - 8040:8040  # VisualDL

  # PaddleSeg with CUDA=10.2 CUDNN=7
  paddleseg_cuda10:
    runtime: nvidia
    build:
      context: ./docker
      dockerfile: Dockerfile
      args:
        CUDA: 10.2
        CUDNN: 7
    tty: true
    volumes:
      - ./output:/paddleseg/output
      - ./data:/paddleseg/data
    ports:
      - 8040:8040  # VisualDL
